BUFFER_SIZE = 1024

# methods
PUT = "PUT"
QUERY = "QUERY"
GET = "GET"
DELETE = "DELETE"

# messages
OK = "OK"
ERROR = "ERROR"
WARNING = "WARNING"
SUCCESS = "SUCCESS"

NOT_FOUND = "NOT_FOUND"
ALREADY_EXISTS = "ALREADY_EXISTS"
BAD_SYNTAX = "BAD_SYNTAX"
REPLICA_IS_DOWN = "REPLICA_IS_DOWN"

CANNOT_GUARANTEE_CORRECT_OUTPUT = "CANNOT_GUARANTEE_CORRECT_OUTPUT"
CANNOT_EXECUTE = "CANNOT_EXECUTE"

